# Generated by Django 3.1.2 on 2020-11-05 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='カテゴリ名')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='品名')),
                ('breakfast', models.BooleanField(default=True, verbose_name='朝メニュー')),
                ('lunch', models.BooleanField(default=True, verbose_name='昼メニュー')),
                ('dinner', models.BooleanField(default=True, verbose_name='夜メニュー')),
                ('takeout', models.BooleanField(default=True, verbose_name='テイクアウト')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menulist.category', verbose_name='カテゴリ名')),
            ],
            options={
                'db_table': 'menu',
            },
        ),
    ]
