# Generated by Django 3.1.2 on 2020-11-05 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menulist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='takeout',
        ),
    ]
