# Generated by Django 3.1.2 on 2020-11-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menulist', '0002_remove_menu_takeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='takeout',
            field=models.BooleanField(default=True, verbose_name='テイクアウト'),
        ),
    ]
